export const request = {
  emotions: [
    {
      type: "Sad",
      reasons: [
        "lost someone close to you",
        "going through a breakup",
        "feeling lonely and isolated",
        "disappointed by life circumstances",
        "dealing with rejection",
        "feeling overwhelmed by responsibilities",
        "missing someone far away",
      ],
    },
    {
      type: "Angry",
      reasons: [
        "someone betrayed your trust",
        "missed an opportunity you deserved",
        "lost something precious to you",
        "messed up something important",
        "being treated unfairly",
        "dealing with injustice or discrimination",
        "frustrated with lack of progress",
        "feeling disrespected or dismissed",
      ],
    },
    {
      type: "Lost",
      reasons: [
        "unsure about your life direction",
        "questioning your career path",
        "feeling stuck in routine",
        "lost sense of purpose or meaning",
        "confused about relationships",
        "uncertain about major life decisions",
        "feeling disconnected from yourself",
        "overwhelmed by too many choices",
      ],
    },
    {
      type: "Scared",
      reasons: [
        "afraid of upcoming changes",
        "anxious about the future",
        "worried about failing",
        "concerned about loved ones' safety",
        "facing a difficult conversation",
        "dealing with health concerns",
        "nervous about new responsibilities",
        "intimidated by new challenges",
        "afraid of being judged",
      ],
    },
    {
      type: "Happy",
      reasons: [
        "achieved a personal goal",
        "received good news",
        "spending time with loved ones",
        "celebrating a special occasion",
        "feeling grateful for what you have",
        "accomplished something meaningful",
        "experiencing new adventures",
        "feeling loved and appreciated",
        "enjoying simple pleasures",
        "feeling optimistic about the future",
      ],
    },
  ],
};
